### ISSUE TITLE
Additional csv files 

### ISSUE THREAD

**Issue by chriss-lz** [ratschlab/circEWS#2]
First of all gratulations to your paper!

I am currently trying to get the model you made available on Github (https://github.com/ratschlab/circEWS) to work for the above-mentioned paper. In the course of this, I noticed that you also used other CSV files in addition to the HiRID and MIMIC III data.
In the script "mimic_paths.py", for example, other CSV files were used in addition to the MIMIC III, e.g. in the folder "ref_lists", "external_validation" or "misc_derived/stephanie". It would be very helpful for me if you can provide all CSV files used outside HiRID and MIMIC III. My understanding is that these are essential to make the model work with validation.

Thanks a lot in advance!

**Comment by mhueser** [comment]
Could you please specify which CSV files you would exactly need, i.e. their file-names as expected in the scripts
you try to run.

**Comment by chriss-lz** [comment]
Thanks for the fast response Matthias! I'm just starting, but for the moment I found e.g. the following csv files:

/cluster/work/grlab/clinical/Inselspital/DataReleases/01-19-2017/InselSpital/external_validation/ref_lists/D_ITEMS.csv
/cluster/work/grlab/clinical/Inselspital/DataReleases/01-19-2017/InselSpital/external_validation/ref_lists/D_LABITEMS.csv
/cluster/work/grlab/clinical/Inselspital/DataReleases/01-19-2017/InselSpital/external_validation/ref_lists/mimic_vars.csv
/cluster/work/grlab/clinical/Inselspital/DataReleases/01-19-2017/InselSpital/external_validation/chunks.csv
/cluster/work/grlab/clinical/Inselspital/DataReleases/01-19-2017/InselSpital/misc_derived/visualisation/id2string_v6.npy
/cluster/work/grlab/clinical/Inselspital/DataReleases/01-19-2017/InselSpital/misc_derived/visualisation/mid2string_v6.npy
/cluster/work/grlab/clinical/Inselspital/DataReleases/01-19-2017/InselSpital/misc_derived/ref_excel/varref_excel_v6.tsv
/cluster/work/grlab/clinical/Inselspital/DataReleases/01-19-2017/InselSpital/misc_derived/ref_excel/labref_excel_v6.tsv

It's great if you can help me there, thanks in advance!

Best regards,

Chris

**Comment by HarrisonWilde** [comment]
Hello, we are trying to do the same reproduction, please could you provide these CSV files?
